name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Commit Information
        id: commit
        run: |
          echo "commit_id=commit-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - name: Create Patch
        run: |
          sudo apt-get install zip unzip -y
          unzip files/files.zip -d files
          pushd scripts
          python main_create.py
          popd
          zip -r out/patch.zip out/exefs out/romfs
      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: patch
          path: |
            out/patch/exefs
            out/patch/romfs
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/patch.zip"
          bodyFile: README.md
          name: ${{ steps.commit.outputs.commit_message }}
          tag: publish
          token: ${{ secrets.GITHUB_TOKEN }}